### ISSUE TITLE
Wrong coorinates in exported geojson files

### ISSUE THREAD

**Issue by spatialhast** [mapbox/vt2geojson#18]
Using vt2geojson tool I convert several pbf tiles from 3 zoom level to geojson files:
```
vt2geojson https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Esri_Childrens_Map/VectorTileServer/tile/3/3/2.pbf > 3_2.geojson
vt2geojson https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Esri_Childrens_Map/VectorTileServer/tile/3/3/1.pbf > 3_1.geojson
vt2geojson https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Esri_Childrens_Map/VectorTileServer/tile/3/2/2.pbf > 2_2.geojson
vt2geojson https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Esri_Childrens_Map/VectorTileServer/tile/3/2/1.pbf > 2_1.geojson
```
But when I open geojson files in QGIS, features have wrong position and tiles order:
![image](https://user-images.githubusercontent.com/3269617/36061820-dcfc70c8-0e68-11e8-9fe6-688091ee2966.png)

Services Directory: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Esri_Childrens_Map/VectorTileServer?cacheKey=aa41ff47603e8df5&f=html

How I can receive geojson files with correct coordinates?
Thanks!

**Comment by AsimAziz** [comment]
Hi @spatialhast , did you able to solve this issue?
I'm facing the same problem with my geoserver layer.

**Comment by spatialhast** [comment]
Hi @AsimAziz , 
no, I did not solve this issue

**Comment by jgravois** [comment]
this is because Esri tiles are `z/y/x` and this lib expects `z/x/y`.

this produces the correct results:
```bash
vt2geojson -x 2 -y 3 -z 3 https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Esri_Childrens_Map/VectorTileServer/tile/3/3/2.pbf > out.geojson
```
![Screen Shot 2020-05-07 at 5 52 38 PM](https://user-images.githubusercontent.com/3011734/81358504-900f5800-908b-11ea-9a34-58bed1fe9ce7.png)
