### ISSUE TITLE
Invalid layer name crash

### ISSUE THREAD

**Issue by benwong0** [mapbox/vt2geojson#8]
In line 78 of index.js
```
77: var layer = tile.layers[layerID];
78: for (var i = 0; i < layer.length; i++) {
```
it crashes if layer is undefined, which could happen from an invalid layer ID or a layer that don't exist in current tile. Putting an if check `if (layer)` would solve it.

**Comment by mapsam** [comment]
Thanks @benwong0! This was resolved by @amishas157 in #10
